import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";

const popins = Poppins({
  display: 'block',
  weight: ['100', '200', '400', '500', '600', '700',],
  subsets: ['latin'],
  variable: "--font-popins",
});
const inter = Inter({
  display: 'block',
  weight: ['100', '200', '400', '500', '600', '700',],
  subsets: ['latin',],
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${popins.variable} , ${inter.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative">
          <div className="sticky z-1 top-0">
            <Navbar/>
          </div>
          <div>
            {children}
            <Footer/>
          </div>
        </div>
      </body>
    </html>
  );
}
